-- 코드를 입력하세요
SELECT o.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO AS o
RIGHT JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS m ON o.FOOD_TYPE = m.FOOD_TYPE AND o.FAVORITES = m.MAX
ORDER BY o.FOOD_TYPE DESC;