-- 코드를 입력하세요
SELECT c1.CART_ID FROM (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
) AS c1
JOIN (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
) AS c2
ON c1.CART_ID = c2.CART_ID
GROUP BY c1.CART_ID
