SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS m
INNER JOIN REST_REVIEW AS r ON m.MEMBER_ID = r.MEMBER_ID
WHERE m.MEMBER_ID = ANY(
    SELECT MEMBER_ID FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(MEMBER_ID) = (
        SELECT MAX(CNT) FROM (
            SELECT COUNT(MEMBER_ID) AS CNT FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) AS COUNTED
    )
)
ORDER BY r.REVIEW_DATE;