-- 코드를 입력하세요
WITH HISTORY AS (
    SELECT c.CAR_TYPE, c.DAILY_FEE, h.HISTORY_ID, DATEDIFF(h.END_DATE, h.START_DATE) + 1 AS DAY
    FROM CAR_RENTAL_COMPANY_CAR c
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    ON c.CAR_ID = h.CAR_ID
    WHERE c.CAR_TYPE = '트럭' 
)

SELECT HISTORY_ID, 
    CASE
        WHEN DAY < 7
            THEN ROUND(DAILY_FEE * DAY)
        WHEN DAY < 30
            THEN ROUND(DAILY_FEE * DAY * (100 - (
                SELECT DISCOUNT_RATE
                FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                WHERE CAR_TYPE = '트럭' AND DURATION_TYPE LIKE '7%'
            )) / 100)
        WHEN DAY < 90
            THEN ROUND(DAILY_FEE * DAY * (100 - (
                SELECT DISCOUNT_RATE
                FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                WHERE CAR_TYPE = '트럭' AND DURATION_TYPE LIKE '30%'
            )) / 100)
        ELSE ROUND(DAILY_FEE * DAY * (100 - (
            SELECT DISCOUNT_RATE
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE CAR_TYPE = '트럭' AND DURATION_TYPE LIKE '90%'
        )) / 100)
    END AS FEE
FROM HISTORY
GROUP BY HISTORY_ID
ORDER BY 2 DESC, 1 DESC;